# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(223, 261)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.cost_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.cost_edit.setObjectName("cost_edit")
        self.gridLayout.addWidget(self.cost_edit, 4, 1, 1, 2)
        self.taste_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.taste_edit.setObjectName("taste_edit")
        self.gridLayout.addWidget(self.taste_edit, 3, 1, 1, 2)
        self.beans_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.beans_edit.setObjectName("beans_edit")
        self.gridLayout.addWidget(self.beans_edit, 2, 1, 1, 2)
        self.roast_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.roast_edit.setObjectName("roast_edit")
        self.gridLayout.addWidget(self.roast_edit, 1, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 6, 2, 1, 1)
        self.volume_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.volume_edit.setObjectName("volume_edit")
        self.gridLayout.addWidget(self.volume_edit, 5, 1, 1, 2)
        self.button = QtWidgets.QPushButton(self.centralwidget)
        self.button.setObjectName("button")
        self.gridLayout.addWidget(self.button, 6, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.title_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.title_edit.setObjectName("title_edit")
        self.gridLayout.addWidget(self.title_edit, 0, 1, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Изменение данных"))
        self.button.setText(_translate("MainWindow", "OK"))
        self.label_5.setText(_translate("MainWindow", "Описание вкуса"))
        self.label_4.setText(_translate("MainWindow", "Молотый/В зёрнах"))
        self.label_6.setText(_translate("MainWindow", "Цена"))
        self.label_3.setText(_translate("MainWindow", "Степень обжарки"))
        self.label_2.setText(_translate("MainWindow", "Название сорта"))
        self.label_7.setText(_translate("MainWindow", "Объём упаковки"))
